# Generated by Django 5.1.6 on 2025-02-21 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('show', models.CharField(max_length=100)),
                ('seat', models.CharField(max_length=50)),
                ('booking_time', models.DateTimeField()),
                ('total_price', models.FloatField()),
                ('is_paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moive_name', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=75)),
                ('gener', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.CharField(max_length=100)),
                ('time', models.TimeField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
